In [1]:
from ultralytics import YOLO
import torch

In [2]:
model = YOLO('yolov8n-pose.pt')

In [4]:
results = model.predict('datasets/test/3000.png', save=True)


image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\test\3000.png: 640x640 8 persons, 123.0ms
Speed: 25.0ms preprocess, 123.0ms inference, 111.5ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\pose\predict


In [8]:
for result in results:
    for keypoints in result.keypoints:
        print(keypoints.xyn[0])

tensor([[0.3571, 0.0930],
        [0.3624, 0.0847],
        [0.3479, 0.0835],
        [0.0000, 0.0000],
        [0.3196, 0.0840],
        [0.3636, 0.1377],
        [0.2825, 0.1294],
        [0.3871, 0.2060],
        [0.2567, 0.1832],
        [0.4296, 0.2490],
        [0.3058, 0.1873],
        [0.3540, 0.2733],
        [0.2978, 0.2750],
        [0.3693, 0.3757],
        [0.2861, 0.3820],
        [0.3664, 0.4808],
        [0.2725, 0.4840]], device='cuda:0')
tensor([[0.1848, 0.1160],
        [0.2013, 0.1087],
        [0.1791, 0.1048],
        [0.2219, 0.1163],
        [0.0000, 0.0000],
        [0.2303, 0.1641],
        [0.1319, 0.1661],
        [0.2354, 0.2250],
        [0.1017, 0.2311],
        [0.1591, 0.2264],
        [0.1105, 0.2299],
        [0.1936, 0.3071],
        [0.1293, 0.3080],
        [0.1956, 0.4116],
        [0.1471, 0.4248],
        [0.1799, 0.5024],
        [0.1717, 0.5300]], device='cuda:0')
tensor([[0.1550, 0.0818],
        [0.1670, 0.0743],
        [0.1474, 0.0707],
  

In [19]:
import os
import torchvision.transforms as tt
import torchvision.io
from torchvision.utils import save_image
path_to_photo = 'weapon-detection-6/train/images/'
path_to_label = 'weapon-detection-6/train/labels/'
dr = os.listdir(path_to_photo[:-1])
for i in range(len(dr)):
    with open(path_to_label + dr[i][:-4] + '.txt', 'r') as f:
        j = 0
        line = f.readline()
        while len(line) > 0:
            if line[0] == '0':
                tlbr = [float(x) for x in line.split()[1:]]
                image = torchvision.io.read_image(path_to_photo + dr[i])
                width = image.size()[1]
                height = image.size()[2]
                image = tt.functional.resized_crop(image, top=round((tlbr[1]-tlbr[3]/2)*height), left=round((tlbr[0]-tlbr[2]/2)*width),
                                                  width=round(tlbr[2]*width), height=round(tlbr[2]*height), size=width)
                save_image(image / 255, f'datasets/pose_ds/images/{i}_{j}.jpg')
                results = model.predict(f'datasets/pose_ds/images/{i}_{j}.jpg')[0].keypoints.xyn[0]
                if len(results) > 0:
                    zero_arr = torch.zeros(height, width)
                    for point in results:
                        zero_arr[min(torch.round(point[1] * height).cpu().numpy(), 639)][min(torch.round(point[0] * width).cpu().numpy(), 639)] = 1
                    save_image(zero_arr, f'datasets/pose_ds/points/{i}_{j}.jpg')
                    j += 1
            line = f.readline()

C:\Users\vadim_jfdr\anaconda3\envs\tf\lib\site-packages\torchvision\transforms\functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\0_0.jpg: 640x640 2 persons, 39.0ms
Speed: 4.0ms preprocess, 39.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\

Speed: 3.0ms preprocess, 15.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\24_1.jpg: 640x640 (no detections), 12.0ms
Speed: 3.0ms preprocess, 12.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\24_1.jpg: 640x640 (no detections), 13.5ms
Speed: 3.0ms preprocess, 13.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\25_0.jpg: 640x640 (no detections), 12.0ms
Speed: 4.0ms preprocess, 12.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\25_0.jpg: 640x640 1 person, 12.0ms
Speed: 3.0ms preprocess, 12.0ms inference, 3.0ms postprocess per image 

Speed: 4.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\36_0.jpg: 640x640 (no detections), 14.0ms
Speed: 3.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\36_0.jpg: 640x640 (no detections), 14.0ms
Speed: 3.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\37_0.jpg: 640x640 1 person, 13.5ms
Speed: 3.0ms preprocess, 13.5ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\37_1.jpg: 640x640 (no detections), 19.0ms
Speed: 3.0ms preprocess, 19.0ms inference, 1.0ms postprocess per image 


image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\45_0.jpg: 640x640 (no detections), 23.5ms
Speed: 3.0ms preprocess, 23.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\45_0.jpg: 640x640 1 person, 11.0ms
Speed: 3.0ms preprocess, 11.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\45_1.jpg: 640x640 (no detections), 10.6ms
Speed: 2.0ms preprocess, 10.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\45_1.jpg: 640x640 (no detections), 10.0ms
Speed: 3.0ms preprocess, 10.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\

Speed: 3.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\53_0.jpg: 640x640 (no detections), 16.0ms
Speed: 3.0ms preprocess, 16.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\53_0.jpg: 640x640 1 person, 11.4ms
Speed: 3.0ms preprocess, 11.4ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\53_1.jpg: 640x640 (no detections), 13.0ms
Speed: 4.0ms preprocess, 13.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\53_1.jpg: 640x640 (no detections), 14.5ms
Speed: 3.0ms preprocess, 14.5ms inference, 1.0ms postprocess per image 


image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\62_1.jpg: 640x640 (no detections), 15.0ms
Speed: 4.0ms preprocess, 15.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\63_0.jpg: 640x640 (no detections), 14.0ms
Speed: 4.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\63_0.jpg: 640x640 1 person, 14.5ms
Speed: 3.0ms preprocess, 14.5ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\63_1.jpg: 640x640 (no detections), 15.0ms
Speed: 4.0ms preprocess, 15.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\

Speed: 3.0ms preprocess, 15.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\74_1.jpg: 640x640 (no detections), 14.0ms
Speed: 3.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\74_1.jpg: 640x640 1 person, 14.0ms
Speed: 3.0ms preprocess, 14.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\75_0.jpg: 640x640 (no detections), 13.0ms
Speed: 3.0ms preprocess, 13.0ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\75_0.jpg: 640x640 (no detections), 14.0ms
Speed: 4.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image 

Speed: 4.0ms preprocess, 14.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\114_1.jpg: 640x640 (no detections), 13.0ms
Speed: 5.0ms preprocess, 13.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\115_0.jpg: 640x640 2 persons, 14.0ms
Speed: 4.0ms preprocess, 14.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\115_1.jpg: 640x640 1 person, 15.0ms
Speed: 3.0ms preprocess, 15.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\118_0.jpg: 640x640 1 person, 14.0ms
Speed: 4.0ms preprocess, 14.0ms inference, 2.0ms postprocess per image at shape 

Speed: 4.0ms preprocess, 13.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\155_2.jpg: 640x640 2 persons, 20.0ms
Speed: 4.0ms preprocess, 20.0ms inference, 5.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\156_0.jpg: 640x640 (no detections), 13.0ms
Speed: 3.0ms preprocess, 13.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\156_0.jpg: 640x640 1 person, 14.0ms
Speed: 3.0ms preprocess, 14.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\157_0.jpg: 640x640 (no detections), 13.0ms
Speed: 3.0ms preprocess, 13.0ms inference, 1.0ms postprocess per image at


image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\162_3.jpg: 640x640 1 person, 14.5ms
Speed: 3.0ms preprocess, 14.5ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\162_4.jpg: 640x640 (no detections), 14.0ms
Speed: 3.0ms preprocess, 14.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\162_4.jpg: 640x640 (no detections), 15.0ms
Speed: 3.0ms preprocess, 15.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon\ml\datasets\pose_ds\images\163_0.jpg: 640x640 (no detections), 13.0ms
Speed: 6.0ms preprocess, 13.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 C:\Users\vadim_jfdr\OneDrive\\\Video-Detecting-Hackathon

IndexError: index 416 is out of bounds for dimension 0 with size 416